name: Deploy Virtual RDP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      xvfb:
        runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd backend
        npm install
        npm install ngrok
        
    - name: Start Virtual Browser with Ngrok
      run: |
        cd backend
        nohup node server.js &
        echo "RDP Endpoint: $(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        DISPLAY: :99
