version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["npm", "start"]
